export default function TermsAndConditions() {
    return (
        <div className="terms-page">
            <h2>Terms And Conditions</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non nibh tortor. Morbi dignissim lobortis nunc vitae egestas. Nulla id lorem felis. Aenean ultrices leo neque, eget blandit dolor tristique at. Vestibulum lacinia lorem augue, nec porta velit finibus eget. Sed placerat, mi a facilisis cursus, felis sem convallis tellus, a lacinia nulla velit sit amet mauris. Aliquam ultricies lacus quis risus egestas maximus. Sed condimentum diam vel est ullamcorper, ut blandit erat suscipit. Maecenas in nibh imperdiet, tincidunt est sed, placerat mauris. Phasellus luctus, sapien mollis euismod euismod, massa risus efficitur felis, at maximus libero ligula vitae urna. Curabitur et sapien accumsan, porta justo id, tempus metus.</p>
            <p>Sed id condimentum ante. Cras venenatis felis vitae libero ornare ornare. Aliquam pulvinar mauris non neque mattis, eu consequat neque euismod. Pellentesque ut turpis eget urna dapibus consequat. Morbi at tellus ut tellus suscipit tincidunt. Phasellus vel ligula fermentum, varius leo vel, euismod nulla. Quisque feugiat urna et velit tristique fermentum at pellentesque lectus. Proin porttitor est a luctus semper. Sed pulvinar mollis auctor. Vestibulum semper urna ex, a auctor enim venenatis vel. In mattis quam sed velit fermentum venenatis. Aenean elementum mi eget leo vulputate, a imperdiet sem euismod. Curabitur finibus tortor mauris, id porta leo accumsan at. Curabitur viverra, diam sed congue imperdiet, enim libero cursus libero, ut fermentum libero justo et sem. Suspendisse scelerisque diam vestibulum enim gravida suscipit. Aliquam erat volutpat.</p>
            <p>Etiam iaculis rhoncus ipsum quis commodo. Aliquam in lacus cursus, vehicula massa viverra, commodo lectus. Nunc elementum odio eget ante aliquet, in aliquam dui auctor. Donec tincidunt venenatis tellus sed maximus. Donec tincidunt nibh quis justo aliquam egestas. Aliquam erat volutpat. Suspendisse potenti. Suspendisse ac feugiat eros. Integer ac elementum neque. Vestibulum dignissim, lacus in aliquet pretium, lectus arcu malesuada libero, et facilisis sem magna id est.</p>
            <p>Nulla sed commodo sapien. Aliquam sed ultrices enim, sed dapibus nisi. Vestibulum ligula erat, auctor et laoreet vel, fringilla a massa. Curabitur blandit accumsan lacus, at mollis metus convallis eu. Nullam suscipit vel dui eu blandit. Maecenas volutpat dolor sit amet sodales volutpat. Pellentesque sit amet orci sed justo lacinia pellentesque sed vel ligula.</p>
            <p>Aliquam erat volutpat. Nam commodo diam id consectetur imperdiet. Fusce laoreet enim arcu, at porta lorem auctor non. Nam posuere elit gravida euismod sodales. Etiam et neque id nisl vulputate tempus. Aliquam in dictum purus, consequat egestas nisl. Maecenas porta sem eget pharetra suscipit. In ut aliquam odio. Nam at sapien sit amet urna molestie mattis. Suspendisse posuere vitae ex at sodales. Donec vel ante at nunc vestibulum malesuada ac ut ex. Nunc eget sapien non arcu porta mattis ac ut nulla. Vivamus ullamcorper maximus malesuada. Nunc tempus arcu non lacus ultricies, nec dictum nulla molestie. Sed sit amet ligula vitae enim viverra interdum. Aenean sed ultricies orci.</p>
        </div>
    )
}